@startuml
abstract class User {
    id: Long
    name : String
    email: String
    phone: String
    role: CLIENT | FREELANCER | ADMIN
}   

class Freelancer {
    status: boolean 
    membership: boolean
}

class Chat {
    id: Long
    timestamp: localDate
    content: String
}

class Client {
     company: String
}


class TechnologyType {
    type: String
    name: String
}


class Project {
    id: Long
    date: LocalDate
    endDate: LocalDate
    budget: Decimal
    status: WORKING | OPEN | CLOSED
    description: String

}

class Profile {
    description: String
    hourlyRate: Decimal
}

class Rating {
    value: integer
    comment: String
}


class Admin {
    permissions: List<String>
}

User              <|--             Client
User              <|--             Freelancer
User              <|--             Admin
Project      o--  "0.*"   TechnologyType
Project "0..*"   -l-     "0..1"  Client            : has ->
Project "0..*"   -r-     "0..*"  Freelancer      : <- has
Freelancer *-- "0..1" Profile
Chat "0..*"   -l-     "0..1"  User            : has ->
Profile o--> "0..*" Rating
Project "0..1" -r- "0..*" Rating
@enduml
