@startuml
abstract class User {
    id: Long
    name: String
    email: String
    phone: String
}   

class Freelancer {
    active: boolean 
    coins: integer
    chat: Chat
}

class Client {
    company: String
    coins: integer
    chat: Chat
}

class TechnologyType {
    type: String
    name: String
}

class Project {
    id: Long
    date: LocalDate
    endDate: LocalDate
    budget: Decimal
    status: WORKING | OPEN | CLOSED
    description: String
    ratings: List<Rating>
}

class Profile {
    description: String
    hourlyRate: Decimal
}

class Rating {
    value: integer
    comment: String
}

class Admin {
    permissions: List<String>
}

class Chat {
    messages: List<String>
}

User <|-- Client
User <|-- Freelancer
User <|-- Admin

Project o-- "0.*" TechnologyType
Project "0..1" -l- "0..1" Client : has ->
Project "0..*" -r- "0..1" Freelancer : <- has
Freelancer *-- "0..1" Profile
Profile o--> "0..*" Rating
Project "0..*" -- "0..*" Rating
Freelancer "0..1" -- "0..*" Chat
Client "0..1" -- "0..*" Chat
@enduml
