![Casos de Uso](https://www.plantuml.com/plantuml/png/VP3RIWCn48RlynH3xrkwq0D8APLLqGkXM7o0CJkx7Pl3aio2HNntZQRAjejN8Tzyaya_coWOfBD66Qe5n4FWPYzGSI0jx9sA1tOj1hJGeZvWGpiv6e9KLg1KEj4rNsIqDIYr3tO4xme0e8kaCQP2zs9Oen1iWtybBN446E6vdFtZrMmeQ_E-zeYEQue23queK9IiBVfQwLtDmS8MWx3c5bESh2wJcbfWDPcaErp1QaLlGgvQdps3JfE1MziQVxJaJjEAQTzxol-kElsh57rbHnZq7kuvYW_7apIxI8SDGOb2ZGzCyUITRu4gJYDlEEeknhzinL9zg6_tkhBiO3nUv_PpzBE5kq1aKiYG-NmOBuPnCHtcELTfc9naDe0MbwYO3h1YWCtKXbpLMVC9)
